name: build_gst_rs_tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        default: '0.13.6'
        required: true

jobs:
  build_gst_rs:
    runs-on: ubuntu-24.04-arm

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装依赖
    - name: Setup apt
      run: |
        sudo apt update
        sudo apt install -y \
        build-essential \
        git \
        meson \
        ninja-build \
        cargo \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        libclang-dev \
        libssl-dev \
        libsoup2.4-dev \
        libcairo2-dev \
        libpango1.0-dev \
        libunwind-dev
        pkg-config --modversion gstreamer-webrtc-1.0

    # 安装rush
    - name: Setup rush
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"
        rustup default stable

    # 获取源码
    - name: Get Git
      run: |
        git clone https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git
        cd gst-plugins-rs
        git checkout ${{ inputs.tag_name }}
        #cargo build --release
        #ls
        cargo install cargo-c
        cargo cbuild
        
    # 查看目录
    - name: Look
      run: |
        ls
        tree

    # 上传
    - name: Archive ZIP
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.tag_name }}-x86_64
        path: |
          gst-plugins-rs/target/CACHEDIR.TAG
          gst-plugins-rs/target/release/*.so
          gst-plugins-rs/target/release/*.d
        overwrite: true
        compression-level: 9
        retention-days: 3
